import subprocess
from pathlib import Path
from models import ResumeDocument, SourceFile
from parser import parse_file

def assemble(doc: ResumeDocument) -> str:
    """Build the output .tex string from the document model."""
    parts = [doc.preamble, doc.header]

    for section in doc.sections:
        if not section.selected:
            continue

        selected_entries = [e for e in section.entries if e.selected]
        parts.append(section.raw_header)

        if selected_entries:
            parts.append(section.list_prefix)
            for entry in selected_entries:
                parts.append(entry.raw_text)
            parts.append(section.list_suffix)

    parts.append(doc.trailing)
    return ''.join(parts)


def parse_and_assemble_source(source_path: str) -> tuple[SourceFile, str]:
    """Parse source via persistence integration and return (doc, assembled_tex)."""
    doc = parse_file(source_path)
    return doc, assemble(doc)


def write_tex(content: str, path: str) -> None:
    """Write assembled content to a .tex file."""
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)


def _cleanup_latex_intermediates(tex_path: str, output_dir: str) -> None:
    """Delete common LaTeX byproducts and original .tex file, only keeping .pdf files."""
    stem = Path(tex_path).stem
    base = Path(output_dir)

    extensions = {
        '.aux',
        '.log',
        '.out',
        '.toc',
        '.lof',
        '.lot',
        '.fls',
        '.fdb_latexmk',
        '.synctex.gz',
        '.nav',
        '.snm',
        '.vrb',
        '.xdv',
        '.dvi',
        '.bbl',
        '.blg',
        '.bcf',
        '.run.xml',
        '.tex',
    }

    for ext in extensions:
        artifact = base / f'{stem}{ext}'
        try:
            artifact.unlink(missing_ok=True)
        except OSError:
            # Best effort cleanup; non-critical if a file cannot be removed.
            continue


def compile_pdf(tex_path: str, output_dir: str) -> tuple[bool, str]:
    """
    Run pdflatex twice on tex_path, placing output in output_dir.
    Returns (success, log_output).
    On success, removes common intermediate files generated by pdflatex.
    Raises FileNotFoundError if pdflatex is not on PATH.
    """
    cmd = [
        'pdflatex',
        '-interaction=nonstopmode',
        f'-output-directory={output_dir}',
        tex_path,
    ]

    log_lines = []
    for _pass in range(2): # latex is quirky and needs multiple passes for references
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                cwd=output_dir,
            )
            log_lines.append(result.stdout)
            if result.returncode != 0:
                combined = '\n'.join(log_lines)
                tail = '\n'.join(combined.splitlines()[-20:])
                return False, tail
        except FileNotFoundError:
            raise

    _cleanup_latex_intermediates(tex_path, output_dir)

    return True, '\n'.join(log_lines)
